# Generated by Django 4.2 on 2023-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
        migrations.AddField(
            model_name='answerlike',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='vote',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
    ]
