# Generated by Django 4.2 on 2023-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_like_status_answerlike_correct_like_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='app.tag'),
        ),
    ]
